import { Injectable } from '@angular/core';
import { Product } from '../product';

@Injectable()
export class DataService {
  products: Product[] = [
    {name: 'Abrikozen', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Ananas', category: 'Fruit', amount: 0, unit: 'stuk', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Appelen', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Bananen', category: 'Fruit', amount: 0, unit: 'tros', image: 'bananen.png', note: 'Fair trade', shop: 'Delhaize',
      isFixedShop: true, inPromotion: false},
    {name: 'Blauwbessen', category: 'Fruit', amount: 0, unit: 'bakje', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Citroen', category: 'Fruit', amount: 0, unit: 'stuk', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Clementines', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Druiven', category: 'Fruit', amount: 0, unit: 'tros', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Frambozen', category: 'Fruit', amount: 0, unit: 'bakje', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kersen', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kiwi', category: 'Fruit', amount: 0, unit: 'stuk', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kruisbessen', category: 'Fruit', amount: 0, unit: 'bakje', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Limoen', category: 'Fruit', amount: 0, unit: 'stuk', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Mandarijn', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Nectarines', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Peren', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Perziken', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pompelmoes', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pruimen', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sinaasappel', category: 'Fruit', amount: 0, unit: 'kg', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Aardappelen', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Aardappelen', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Asperges', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Aubergine', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Champignons', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Courgette', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Gele paprika', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Groene Asperges', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Groene paprika', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Groene selder', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Knoflook', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Komkommer', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Koolrabi', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Maïs', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Paprika', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pompoen', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Prei', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Radijsjes', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rode biet', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rode paprika', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Selder', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sla', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Spinazie', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'trueTomaten', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'trueUien', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Venkel', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Witte selder', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Wortelen', category: 'Groenten', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Biefstuk', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
    isFixedShop: false, inPromotion: false},
    {name: 'Chipolata', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Cordon blue', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Eendenborst', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Gehakt', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kalfslapje', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
    isFixedShop: false, inPromotion: false},
    {name: 'Kalfsschnitzel', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kalkoenfilet', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kipfilet', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kippenbil', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kippenschnitzel', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kippenworst', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Konijn', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kotelet', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Lamskotelet', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
    isFixedShop: false, inPromotion: false},
    {name: 'Lamskroon', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
    isFixedShop: false, inPromotion: false},
    {name: 'Paardensteak', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
    isFixedShop: false, inPromotion: false},
    {name: 'Saté', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Schnitzel', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Varkenslapje', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '',
    isFixedShop: false, inPromotion: false},
    {name: 'Worst', category: 'Beenhouwerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Brasem', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Forel', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Garnalen', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Gerookte makreel', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Gerookte zalm', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Haring', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kabeljauw', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kreeft', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Maatjes', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Makreel', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Mosselen', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Oesters', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rog', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Schol', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Tong', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Tonijn', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Zalm', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Zeebaars', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Zeewolf', category: 'Vis', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Beemster', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Belegen kaas blok', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Belegen kaas sneden', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Brie', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Comté', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Emmental', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Feta', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Geitenkaas', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Geraspte kaas', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Gorgonzola', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Gouda', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Gruyère', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Jonge kaas blok', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Jonge kaas sneden', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kruidenkaas', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Mascarpone', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Mozzarella', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Oude kaas blok', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Oude kaas sneden', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Parmezaan', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Plattekaas', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Ricotta', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Roquefort', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Smeerkaas', category: 'Kaas', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Amandelmelk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Boter', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Chocomelk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Chocomousse', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Culinaire room', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Drinkyoghurt', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Eieren', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Fruityoghurt', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Griekse yoghurt', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Halfvolle melk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Havermelk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Hoeveboter', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Karnemelk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Magere melk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Magere yoghurt', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Margarine', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Melk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pudding', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rijstmelk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rijstpap', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Room', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Slagroom', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sojamelk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sojaroom', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Tiramisu', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Volle melk', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Yoghurt', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Zure room', category: 'Zuivel', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Arborio rijst', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Basmatirijst', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Boekweit', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Bulgur', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Cappellini', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Couscous', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Gnocchi', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Lasagne', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Noedels', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Pasta', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Penne', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Quinoa', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Rijst', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Rode rijst', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Spaghetti', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Tagliatelle', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Tarwe', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Volle rijst', category: 'Pasta-granen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Aardbeienconfituur', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Abrikozenconfituur', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Beschuiten', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Choco', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Confituur', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Corn flakes', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Cruesli', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Hagelslag', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Honing', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Maïswafels', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Muesli', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pindakaas', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rijstwafels', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Speculaaspasta', category: 'Ontbijt', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Aardbeientaart', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Appeltaart', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Ciabatta', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Donut', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Eclair', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Focaccia', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Fruittaart', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Meergranenbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Picolo', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pistolets', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Roggebrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rozijnenbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Sandwich', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Speltbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Stokbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Suikerbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Volkorenbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Witbrood', category: 'Bakkerij', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Basilicum', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Bieslook', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Cajun', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Cayennepeper', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Chilipeper', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Dille', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Dragon', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Jeneverbessen', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kaneel', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kerrie', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Komijn', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Koriander', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kruidnagel', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kurkuma', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Muskaatnoot', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Oregano', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Paprikapoeder', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Roze peper', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Rozemarijn', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Saffraan', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'StoofBeenhouwerijkruiden', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Thijm', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Vanillestokjes', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Witte peper', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Zout', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Zwarte peper', category: 'Specerijen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Ajuintjes', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Ansjovis', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Appelmoes', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Augurken', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Borlottibonen', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Cassoulet', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Fruitsalade', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kappertjes', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Makreel', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Palmharten', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Perziken', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Ravioli', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Rode bonen', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sardine', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Tomatenblokjes', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Tomatenpuree', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Tonijn', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Veenbessen', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Witte bonen in tomatensaus', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Zalm', category: 'Conserven', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Bolognese', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Ketchup', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Mayonaise', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Mosterd', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Pesto', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sojasaus', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Tabasco', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Tikka Masala', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Worcester saus', category: 'Sauzen', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Bosvruchten', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Chocolade-ijs', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Citroensorbet', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Erwten', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Fishsticks', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Frambozen', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Frieten', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Frisco\'s', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Garnalen', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Kipnuggets', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Kroketten', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Loempia\'s', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Pizza', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Raket', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Roomijs', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Sorbet', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Spinazie', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '', isFixedShop: false, inPromotion: false},
    {name: 'Vanille-ijs', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false},
    {name: 'Zeevruchten', category: 'Diepvries', amount: 0, unit: '', image: '', note: '', shop: '',
      isFixedShop: false, inPromotion: false}
  ];
  categories: string[] = [
    'Fruit',
    'Groenten',
    'Beenhouwerij',
    'Vis',
    'Kaas',
    'Zuivel',
    'Pasta-granen',
    'Ontbijt',
    'Bakkerij',
    'Specerijen',
    'Conserven',
    'Sauzen',
    'Diepvries'
  ];
  units: string[] = [
    'g',
    'kg',
    'Stuk',
    'Zakje',
    'Bakje',
    'Netje',
    'Pot',
    'Tros',
    'Bussel',
    'Kist',
    'Karton'
  ];

  constructor() { }

  getProducts(pCategory: String) {
    const result: Product[] = [];
    for (const product of this.products) {
      if (product.category === pCategory) {
        result.push(product);
      }
    }

    return result;
  }

  getCategories() {
    return this.categories;
  }

  getUnits() {
    return this.units;
  }

}
